export const business={businessName:'NS Clinic',phone:'07453 296000',whatsapp:'447453296000',address:['Swinnow Crescent','Stanningley','Pudsey','Leeds','LS28 6NZ','United Kingdom'],city:'Leeds',postcode:'LS28 6NZ',openingHours:null,bookingURL:null,instagram:null,facebook:null,treatwellURL:null,googleMapsURL:'https://www.google.com/maps/search/?api=1&query=Swinnow+Crescent+Stanningley+Pudsey+LS28+6NZ',practitioner:{name:null,title:null,qualifications:null,experience:null,training:null}};
export const BOOKING_URL=business.bookingURL||'/contact';
export const whatsapp=(t?:string)=>`https://wa.me/${business.whatsapp}?text=${encodeURIComponent(t?`Hi NS Clinic, I'm interested in ${t} and would like some more information.`:`Hi NS Clinic, I'm interested in one of your treatments and would like some more information.`)}`;
export const slugify=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export const categories=[
{slug:'facial-aesthetics',name:'Facial Aesthetics',title:'Facial Aesthetics in Leeds',intro:'Explore options for lip shape, facial definition and proportion. Your features, goals and suitability guide the conversation.',image:'lips',names:['Lip Fillers','Russian Lip Fillers','Dermal Fillers','Cheek Fillers','Chin Fillers','Jawline Fillers','Nasolabial Fold Fillers','Marionette Line Fillers','Full Face Filler','Tear Trough Filler','Non-Surgical Rhinoplasty','Facial Contouring','PDO Thread Lift','Anti-Wrinkle Treatments','Gummy Smile Treatment']},
{slug:'skin-treatments',name:'Skin & Skin Boosters',title:'Skin Treatments & Skin Boosters in Leeds',intro:'From hydration to texture, find a starting point for your skin concerns. A consultation helps you understand which options may suit your skin.',image:'skin',names:['Skin Boosters','Jalupro','Sunekos','Pink Glow','Mesotherapy','Microneedling','Dermaplaning','Chemical Peels','Clinical Facials','Microdermabrasion','Skin Lightening','Stretch Mark Reduction','B12 Injections','Vitamin C Treatments','Glutathione']},
{slug:'hifu-advanced-skin',name:'HIFU & Advanced Skin',title:'HIFU & Advanced Skin Treatments',intro:'Advanced non-surgical options for clients interested in skin tightening, rejuvenation and texture improvement. Discuss the available equipment and your suitability with the clinic.',image:'skin',names:['HIFU Face','HIFU Face & Neck','HIFU Body','RF Microneedling','RF Skin Tightening','Endolift','Laser Skin Resurfacing']},
{slug:'body-contouring',name:'Body Contouring',title:'Body Contouring & Fat Reduction Treatments',intro:'Discuss your body concerns and the areas you would like to address. Treatment choice depends on your goals, medical history and assessment.',image:'hero',names:['Fat Dissolving','HIFU Body','Body Contouring','Non-Surgical BBL','Buttock Enhancement','Hip Dip Enhancement','Body Filler']},
{slug:'laser-treatments',name:'Laser Treatments',title:'Laser Treatments in Leeds',intro:'Explore hair reduction, tattoo removal and selected skin treatments. Your skin, the treatment area and the clinic’s available equipment need to be assessed first.',image:'skin',names:['Laser Hair Removal','Laser Tattoo Removal','Laser Skin Treatments']},
{slug:'beauty',name:'Beauty, Lashes & Brows',title:'Beauty, Lashes & Brows',intro:'Considered finishing touches, from a softly defined brow to your preferred lash style. Explore the options and enquire about an appointment.',image:'lips',names:['Classic Lashes','Hybrid Lashes','Russian Lashes','Russian Volume','Wispy Lashes','Lash Infills','Lash Lift','Lash Tint','Brow Tint','Henna Brows','Brow Lamination','Brow Shaping','Brow Definition','Teeth Whitening']}
];
const descriptions:Record<string,string>={
'Lip Fillers':'Explore shape, definition and volume with a plan built around your existing lip proportions.',
'Russian Lip Fillers':'A lip-shaping approach to discuss during consultation, with suitability assessed individually.',
'Dermal Fillers':'Discuss volume and facial proportions, including which areas may be appropriate to treat.',
'Cheek Fillers':'Options for cheek volume and definition, planned around your facial structure.',
'Chin Fillers':'Discuss chin proportion and its relationship to your wider facial profile.',
'Jawline Fillers':'Explore jawline definition and balance through an individual facial assessment.',
'Nasolabial Fold Fillers':'Discuss the folds between the nose and mouth and whether filler is appropriate.',
'Marionette Line Fillers':'Explore options for the lines extending down from the corners of the mouth.',
'Full Face Filler':'A wider facial assessment to consider how different areas work together.',
'Tear Trough Filler':'Under-eye treatment enquiries require a careful suitability and risk assessment.',
'Non-Surgical Rhinoplasty':'Discuss selected nose-profile concerns, the limitations of filler and potential risks.',
'Facial Contouring':'Consider shape and facial balance with a tailored treatment discussion.',
'PDO Thread Lift':'Enquire about thread-based treatments, suitability, limitations and recovery.',
'Anti-Wrinkle Treatments':'A consultation to discuss line-related concerns and appropriate treatment options.',
'Gummy Smile Treatment':'Discuss smile-related concerns and whether a suitable treatment is available.',
'Skin Boosters':'Discuss injectable options intended to support skin hydration and skin quality.',
'Jalupro':'Enquire about Jalupro, the formulation offered and whether it suits your skin concerns.',
'Sunekos':'Discuss Sunekos and the clinic’s available skin-booster approach.',
'Pink Glow':'Ask about the formulation, treatment method and availability before booking.',
'Mesotherapy':'Discuss targeted skin treatment options and the products used by the clinic.',
'Microneedling':'A skin treatment to discuss for texture concerns and a personalised skin plan.',
'Dermaplaning':'A surface exfoliation option for selected skin types and concerns.',
'Chemical Peels':'Discuss peel type, skin suitability, expected recovery and aftercare.',
'Clinical Facials':'Choose a facial approach around your current skin concerns and preferences.',
'Microdermabrasion':'Explore surface exfoliation and whether it fits your skin treatment plan.',
'Skin Lightening':'Discuss uneven tone and pigmentation concerns, without promising a change in skin colour.',
'Stretch Mark Reduction':'Explore treatment options for the appearance of stretch marks. Outcomes vary.',
'HIFU Face':'Discuss ultrasound-based options for facial skin tightening and your suitability.',
'HIFU Face & Neck':'Explore a face and neck treatment plan following an individual assessment.',
'HIFU Body':'Discuss selected body areas and whether ultrasound treatment is appropriate.',
'RF Microneedling':'Enquire about combined radiofrequency and microneedling options for texture concerns.',
'RF Skin Tightening':'Discuss radiofrequency-based skin treatment and the equipment available.',
'Endolift':'Enquire about availability, practitioner suitability assessment and treatment details.',
'Laser Skin Resurfacing':'Discuss skin texture concerns, the device used and the expected recovery.',
'Fat Dissolving':'Enquire about selected localised areas, product details and individual suitability.',
'Body Contouring':'Discuss the areas you would like to address and available treatment options.',
'Non-Surgical BBL':'Enquire about the exact method, potential risks and whether this option is available.',
'Buttock Enhancement':'Discuss your goals, the proposed method and an individual suitability assessment.',
'Hip Dip Enhancement':'Explore proportion-related concerns and the available options after assessment.',
'Body Filler':'Ask about the product, treatment area, risks and practitioner assessment.',
'Laser Hair Removal':'Longer-term hair reduction for selected body and facial areas; suitability varies.',
'Laser Tattoo Removal':'Multiple sessions may be required. Tattoo colour, size and skin response affect outcomes.',
'Laser Skin Treatments':'Selected skin laser options; exact treatments and equipment need clinic confirmation.',
'Classic Lashes':'Individual lash extensions for a softly defined look.',
'Hybrid Lashes':'A combination of classic and volume styles tailored to your preference.',
'Russian Lashes':'Discuss a fuller lash style and the finish you prefer.',
'Russian Volume':'Explore volume lashes with a style suited to your natural lashes.',
'Wispy Lashes':'A textured lash style with varied lengths and a softer finish.',
'Lash Infills':'Maintenance appointments for existing extensions, subject to assessment.',
'Lash Lift':'Discuss enhancing the appearance of your natural lash curl.',
'Lash Tint':'A tinting option to add definition to natural lashes.',
'Brow Tint':'Discuss shade and definition for your natural brows.',
'Henna Brows':'Explore henna-based brow colour and your preferred finish.',
'Brow Lamination':'Discuss shaping and styling your brow hairs.',
'Brow Shaping':'A considered shape planned around your natural brows.',
'Brow Definition':'Explore a more defined brow finish with a personalised approach.',
'Teeth Whitening':'Availability and the appropriate dental professional must be confirmed before booking.'};
export const treatments=categories.flatMap(c=>c.names.map(name=>({name,category:c.slug,description:descriptions[name]||'Availability and suitability require final clinic confirmation before public launch.',image:`/images/${c.image}.jpg`,price:null,featured:['Lip Fillers','Anti-Wrinkle Treatments','Dermal Fillers','Skin Boosters','HIFU Face','Microneedling','Fat Dissolving','Laser Hair Removal'].includes(name),link:name==='Lip Fillers'?'/lip-fillers-leeds':`/${c.slug}#${slugify(name)}`,status:['B12 Injections','Vitamin C Treatments','Glutathione','Teeth Whitening','Laser Skin Treatments'].includes(name)?'confirmation-required':'consultation',id:`${c.slug}-${slugify(name)}`})));
export const otherServices=['Hair Restoration','Hair / Scalp Treatments','Vein Treatments'];
export const pages:Record<string,{title:string;description:string}>={treatments:{title:'Treatments at NS Clinic',description:'Browse aesthetics, skin, body, laser and beauty treatments, organised around your goals.'},results:{title:'Before & After Results',description:'Explore the treatment results gallery. Real clinic photography will be added with client permission.'},about:{title:'About NS Clinic',description:'A more personal approach to aesthetics, skin, body and beauty treatments in Stanningley, Leeds.'},contact:{title:'Book or Contact NS Clinic',description:'Discuss a treatment, ask a question or request an appointment at NS Clinic in Stanningley, Leeds.'},reviews:{title:'Client Reviews',description:'A dedicated space for genuine, source-labelled client feedback.'},prices:{title:'Prices & Offers',description:'Explore our treatment categories and request a current, personalised quote.'},areas:{title:'Serving Leeds & Surrounding Areas',description:'One clinic in Stanningley, welcoming clients from Pudsey, Leeds and neighbouring areas.'},'lip-fillers-leeds':{title:'Lip Fillers in Leeds',description:'Explore shape, definition and proportion with a personalised consultation at NS Clinic.'},privacy:{title:'Privacy',description:'How this demo handles your information.'},cookies:{title:'Cookies',description:'Information about browser storage and third-party services.'},terms:{title:'Terms',description:'Using the NS Clinic sales demonstration website.'},'treatment-disclaimer':{title:'Treatment Disclaimer',description:'Important information about treatment enquiries and individual suitability.'}};
